// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE8QsptGMWXwSQd1srS3tk5uXXIebuW-c',
    appId: '1:722161471924:android:2c30940d5d94c6fd2e22e1',
    messagingSenderId: '722161471924',
    projectId: 'hai-social-walking',
    storageBucket: 'hai-social-walking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvdnyTWySz6LLzvi_qEj_kxLf-N0oqZ9Y',
    appId: '1:722161471924:ios:68c74df8916e25272e22e1',
    messagingSenderId: '722161471924',
    projectId: 'hai-social-walking',
    storageBucket: 'hai-social-walking.firebasestorage.app',
    androidClientId: '722161471924-o9oclsdca1oehpspdh7nhkpvm2og5t8f.apps.googleusercontent.com',
    iosClientId: '722161471924-s27g259gli5a8966jg996mjdkpb1svpp.apps.googleusercontent.com',
    iosBundleId: 'com.uva-hai.social-walking-v2',
  );

}